### PR TITLE
Update various project set-up files

### PR DESCRIPTION
**Pull request by dav3r**
This PR updates the README, adds the LICENSE and CONTRIBUTING files.  It also sets up pre-commit, though I have temporarily disabled `bandit` checks because I was unable to test the changes it was recommending (due to some unavailable infrastructure today).

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
Why no TravisCI config and badge?

**Comment by felddy** [comment]
There is a more recent version of the [CONTRIBUTING](https://github.com/cisagov/skeleton-python-library/blob/develop/CONTRIBUTING.md) file in the skeleton-python-library that covers running `pytest`.  While you're over there grab the `setup.py`, `.travis.yml`, `pystest.ini`, and `.coveragerc`.   Get your coverage on yo!

**Comment by dav3r** [comment]
@jsf9k and @felddy thanks for your reviews- please take a look at the latest batch of commits and let me know if you spot anything else that I should add at this juncture.

**Review by jsf9k — APPROVED** [review]
Approved.  I'm on my phone, so I am blindly assuming that coveralls isn't crapping out with no pytest tests being run.

**Review by felddy — APPROVED** [review]
Does `pytest` actually fail?  I think you can leave it enabled in travis.  It should just be a noop.  Worse case is you'll need an empty tests directory.   

LGTM

**Comment by dav3r** [comment]
@jsf9k I will have to check on the next build if coveralls cares about an empty tests directory; I hadn't yet enabled coveralls on this project when the [most recent build ran](https://travis-ci.com/cisagov/assessment-data-export/builds/111092981) (a coveralls exception was thrown, but it didn't cause the build to fail).

@felddy Looks like pytest with an empty tests directory causes the [build to fail](https://travis-ci.com/cisagov/assessment-data-export/builds/110989324).

**Pull request merged**
